---

- hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  roles:
    - role: download_raspbian
      tags:
        - prep_ssd

- hosts: k3s-cluster:children
  vars:
    reset_ssd: false
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
      tags:
        - prep_ssd
    - role: ssd
      tags:
        - ssd_as_root
    - role: system
      tags:
        - system_setup
