---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: master_primary
  become: yes
  roles:
    - role: k3s/master
      tags:
        - primary

- hosts: master_secondaries
  become: yes
  roles:
    - role: k3s/master
      tags:
        - secondary

- hosts: node
  become: yes
  roles:
    - role: k3s/node
