#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

$DIR/.ansible-run.sh \
  -e "raspbian_version=${RASPBIAN_VERSION}" \
  -e "raspbian_image_location=${RASPBIAN_IMAGE_LOCATION}" \
  $DIR/../target/node_setup/site.yml \
  $@
#  -e "reset_nodes=pi-btc" \
